import { Grievance, UserProfile, AuditLogEntry } from "./types";

export const MOCK_USERS: Record<string, UserProfile> = {
  OFFICER: {
    id: "usr-off-01",
    fullName: "Er. Rajesh Sharma",
    role: "OFFICER",
    designation: "Executive Engineer",
    departmentId: "dept-pmc-civil",
    departmentName: "PMC Road Infrastructure & Civil Maintenance",
    jurisdictionName: "Ward 12, Sinhagad Zone, Pune",
    avatarUrl:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBIQi0Wax_aYH0YvIgha4da_y5mQJE-k7LaKsFCkGnd8MCfSABdc1QNU-8X-LeGBu6U5euyrGNPoHs_zmUqFaktsCtcNkOLk0rfnVlanJQ9XrHVLfwpA_e4NeclXfwJJVHup9QVIK6eYdFVHzCzqFw-wZHqu47I6leMKsRr-HFQoK568Z9vVL6NAV3yRz2MBz7K2y8OuA-Pm-YxW6Fur7w0xbAT9bYokIKoJf2s66xZeGhhNd_zUdFW4w",
    email: "rajesh.sharma@punecorporation.gov.in",
    phone: "+91 98230 44102",
  },
  CITIZEN: {
    id: "usr-cit-01",
    fullName: "Ramesh Kulkarni",
    role: "CITIZEN",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    email: "ramesh.kulkarni@gmail.com",
    phone: "+91 98220 54199",
    jurisdictionName: "Sinhagad Road, Ward 12, Pune",
  },
  DEPARTMENT_ADMIN: {
    id: "usr-adm-dept-01",
    fullName: "Sunita Deshpande",
    role: "DEPARTMENT_ADMIN",
    designation: "Superintending Engineer (West Zone)",
    departmentId: "dept-pmc-civil",
    departmentName: "PMC Road Infrastructure & Civil Maintenance",
    email: "sunita.deshpande@punecorporation.gov.in",
    phone: "+91 98225 11090",
  },
  SYSTEM_ADMIN: {
    id: "usr-sys-adm-01",
    fullName: "Dr. Anand Rao, IAS",
    role: "SYSTEM_ADMIN",
    designation: "Additional Municipal Commissioner & Chief Digital Officer",
    departmentName: "Pune Municipal Corporation",
    email: "amc.digital@punecorporation.gov.in",
  },
};

export const INITIAL_GRIEVANCE_1042: Grievance = {
  id: "843d73f3db084240b322a506872dc7ab",
  grievanceNumber: "GRV-2026-1042",
  title: "Severe Road Crater & Exposed Electrical Conduit after Monsoon Inundation near Sinhagad Road Junction",
  description:
    "Deep crater spanning 1.8 meters across opposite Petrol Pump on Sinhagad Road. Exposing live underground electrical wiring casing. Multiple two-wheelers skidded during rain yesterday evening. Urgent repair required before peak evening commute.",
  originalTextLog:
    "Deep crater spanning 1.8 meters across opposite Petrol Pump on Sinhagad Road. Exposing live underground electrical wiring casing. Multiple two-wheelers skidded during rain yesterday evening. Urgent repair required before peak evening commute.",
  language: "Marathi & English Hybrid",
  audioTranscript: {
    marathi:
      "कल रात बारिश के बाद यहाँ बड़ा गड्ढा हो गया है और बिजली की तारें बाहर दिख रही हैं। दो-तीन गाड़ियां फिसल चुकी हैं। कृप्या जल्द से जल्द इसे ठीक करें।",
    model: "Marathi ASR Model v4.2",
    duration: "00:24",
    confidence: 97.8,
  },
  citizen: {
    id: "usr-cit-01",
    name: "Ramesh Kulkarni",
    uid: "IND-MH-PN-8812",
    isVerified: true,
    phoneMasked: "+91 98220 *****",
  },
  filedAt: "2026-09-17T10:32:00.000Z",
  priority: "HIGH",
  status: "ACKNOWLEDGED",
  ledgerHash: "#PMC-2026-SHA256-4029F",
  location: {
    ward: "Ward 12",
    zone: "Sinhagad Zone",
    address: "Opposite HPCL Petrol Pump, Sinhagad Road Junction, Pune",
    latitude: 18.4965,
    longitude: 73.8312,
  },
  sla: {
    slaCode: "SLA-CIV-04",
    totalHours: 72,
    elapsedHours: 48,
    remainingHours: 24,
    deadlineIso: "2026-09-18T18:00:00.000Z",
    escalationLevel: 0,
    status: "ON_TRACK",
    tiers: [
      {
        tierNumber: 1,
        title: "Tier 1: Ward Executive Engineer",
        designation: "Executive Engineer",
        officerName: "Er. Rajesh Sharma",
        triggerCondition: "Currently Managing",
        status: "ACTIVE",
      },
      {
        tierNumber: 2,
        title: "Tier 2: Superintending Engineer",
        designation: "West Zone PMC",
        officerName: "Er. Sunita Deshpande",
        triggerCondition: "Automated Ping if breach +12h (Trigger: T-12h)",
        status: "UPCOMING",
      },
      {
        tierNumber: 3,
        title: "Tier 3: Addl. Municipal Commissioner",
        designation: "PMC Apex Governance",
        officerName: "Dr. Anand Rao, IAS",
        triggerCondition: "Automated Ping if breach +24h (Trigger: T-0h)",
        status: "UPCOMING",
      },
    ],
  },
  evidence: [
    {
      id: "ev-01",
      fileName: "IMG_20260917_102812.jpg",
      fileUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuAnAJFxBqyHHt4J-K6FHGffv49n4Tfg_AVfNQqTcl2U4e8wU9bn-5S4yyoFThRZooBQmEI2CdW3EH0N20qXHZ1eqbnj2Kbsw5znRUtvsAaEbOx19T7OsUjO63tESeyTfkDsdaCja4-HqKanrnGwhhVR3xq2i0_-Po6EpLvi9QGPalaI_p9rVZEqy22eraKdsAjBhuVADfoSq0zr20fW5r_cIQaHXAxGWS1OP6tWNUbs692-YKnDZTo7YA",
      mimeType: "image/jpeg",
      fileSize: 4182900,
      sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
      exifData: {
        device: "Apple iPhone 14 Pro",
        lens: "24mm f/1.78",
        dateTime: "17 Sep 10:28 AM",
        iso: "40",
      },
      coordinates: {
        latitude: 18.4965,
        longitude: 73.8312,
      },
      matchPercentage: 98.4,
      angleDescription: "Primary Cavitation Angle",
      verificationStatus: "LIKELY_AUTHENTIC",
      manipulationScore: 0.04,
      syntheticAiScore: 0.02,
      weatherCorrelation: "IMD Pune 38mm wet ground",
    },
    {
      id: "ev-02",
      fileName: "IMG_20260917_102905.jpg",
      fileUrl:
        "https://lh3.googleusercontent.com/aida-public/AB6AXuD0b0IOJA2Hr9bRQxyEW_8m2AsGVVSdHE31eCePxKOYdEgIRtKS5XmhwHSPmj1BzCSW7-xxv4tahmFSv6WZe0PYQy7QqgfYl1nrYI87EKlCJwACk5OmLZG--XeYOUeqqRuoVTiLUsQdJCj4SvDs8SdpfsTKi7Ix5pvfc3PRILpk3EIMhQKlsEm15s2LUKGmanU7Qfp_ofkJbL8pP3soDTEhJXvdrgePO1pvOvgGXNDRz0_HgFaQvmlLHg",
      mimeType: "image/jpeg",
      fileSize: 3894100,
      sha256: "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce",
      exifData: {
        device: "Apple iPhone 14 Pro",
        bearing: "240° WSW",
        dateTime: "17 Sep 10:29 AM",
      },
      coordinates: {
        latitude: 18.4966,
        longitude: 73.831,
      },
      matchPercentage: 96.1,
      angleDescription: "Road Junction Context View",
      verificationStatus: "LIKELY_AUTHENTIC",
      manipulationScore: 0.03,
      syntheticAiScore: 0.01,
      weatherCorrelation: "IMD Pune 38mm wet ground",
    },
  ],
  aiAnalysis: {
    category: "Road Infrastructure & Public Safety",
    subcategory: "Asphalt Collapse & Utility Cable Exposure",
    severityScore: 8.8,
    severityDescription: "Critical public hazard",
    affectedPopulationEstimate: "~14.5k Commuters / 2-wheelers daily",
    durationText: "3d Worsened post-monsoon",
    jurisdiction: "Dual-Dept: PMC Civil + MSEDCL",
    confidenceScore: 94.2,
    extractedEntities: [
      "Sinhagad Road Junction",
      "HPCL Petrol Outflow",
      "Ward 12 Underground Feeder #4",
    ],
    multimodalSummary:
      "The sub-surface road collapse is directly attributable to hydraulic scouring around a shallow high-voltage power conduit casing installed during recent telecom ducting. The proximity of monsoon standing water to compromised conduit insulation represents an acute electrocution vulnerability for two-wheeler transit during high-tide traffic.",
  },
  similarComplaints: [
    {
      id: "grv-sim-01",
      grievanceNumber: "GRV-2026-0981",
      title: "Pothole near petrol pump after rains",
      similarityScore: 92,
      reportedAt: "16 Sep, 18:40",
      status: "IN_PROGRESS",
    },
    {
      id: "grv-sim-02",
      grievanceNumber: "GRV-2026-1004",
      title: "Exposed cable spark risk near junction",
      similarityScore: 87,
      reportedAt: "17 Sep, 08:15",
      status: "ACKNOWLEDGED",
    },
  ],
  recommendation: {
    recommendedAction:
      "Deploy Quick-Response Asphalt Repair Vehicle #04 & MSEDCL Isolation Crew",
    rationale:
      "Consolidate 3 citizen tickets into one master work order. Pre-insulate high-voltage feeder prior to cold-asphalt compaction to prevent future short circuits. Nighttime weather radar indicates +40mm rainfall in 14 hours.",
    expectedResolutionHours: 4,
    confidenceScore: 95.5,
    status: "PENDING_REVIEW",
  },
  agentTimeline: [
    {
      id: "step-1",
      actor: "CITIZEN",
      title: "Citizen Grievance Logged",
      timestamp: "10:32 AM",
      description: "Ramesh Kulkarni submitted report with 2 geotagged images and Marathi audio complaint.",
      icon: "person",
      isCompleted: true,
    },
    {
      id: "step-2",
      actor: "AI_AGENT",
      title: "AI NLP & Hazard Indexing",
      timestamp: "10:34 AM",
      description: "Risk score assessed at 8.8/10. Identified electrical conduit exposure in standing water.",
      icon: "auto_awesome",
      isCompleted: true,
    },
    {
      id: "step-3",
      actor: "AI_AGENT",
      title: "Autonomous Ticket Routing",
      timestamp: "10:35 AM",
      description: "Assigned directly to Ward 12 Municipal Engineering & Electrical Maintenance Division.",
      icon: "alt_route",
      isCompleted: true,
    },
    {
      id: "step-4",
      actor: "SYSTEM",
      title: "SMS Acknowledged to Citizen",
      timestamp: "10:36 AM",
      description: "Tracking link sent to +91 98220 *****. Citizen opened acknowledgment dossier at 10:39 AM.",
      icon: "sms",
      isCompleted: true,
    },
    {
      id: "step-5",
      actor: "AUTHORITY",
      title: "Authority Inspection Logged",
      timestamp: "11:20 AM",
      description: "Er. Rajesh Sharma deployed joint inspection crew for tomorrow 18 Sep at 10:30 AM.",
      icon: "badge",
      isCompleted: true,
    },
    {
      id: "step-6",
      actor: "AI_AGENT",
      title: "Citizen Status Broadcast Sent",
      timestamp: "11:22 AM",
      description: 'Automated message: "Inspection squad confirmed for 18 Sep 10:30 AM by PMC Ward 12."',
      icon: "check",
      isCompleted: true,
    },
    {
      id: "step-7",
      actor: "AI_AGENT",
      title: "Scheduled Officer Check-in",
      timestamp: "18 Sep, 10:00 AM",
      description: "AI Sentinel pre-inspection reminder and geotag verification prompt to field engineer.",
      icon: "alarm",
      isCompleted: false,
      isPending: true,
    },
  ],
  authorityDirective: {
    officerName: "Er. Rajesh Sharma",
    designation: "Executive Engineer (EE-PMC)",
    loggedAt: "17 Sep 2026, 11:20 AM IST",
    directiveText:
      "Inspection squad deployed with Ward 12 Electrical Maintenance team. Cold mix asphalt patch and cable conduit insulation scheduled for 18 Sep 10:30 AM.",
    aiPolicyVerification:
      "Authority indicates on-site remediation with dual-team coordination. Progressing strictly within Tier-1 SLA workflow. Field equipment checklist verified for bitumen mix and non-conductive casing sleeve.",
  },
};

export const MOCK_GRIEVANCES: Grievance[] = [
  INITIAL_GRIEVANCE_1042,
  {
    id: "grv-2026-1043",
    grievanceNumber: "GRV-2026-1043",
    title: "Garbage collection missed for four days in Shaniwar Peth Lane 4",
    description: "Solid municipal waste accumulation near public school causing hygiene hazard.",
    originalTextLog: "Garbage has not been picked up since Monday. Dogs scattering refuse across lane.",
    language: "English",
    citizen: {
      id: "usr-cit-02",
      name: "Priya Joshi",
      uid: "IND-MH-PN-4401",
      isVerified: true,
      phoneMasked: "+91 97640 *****",
    },
    filedAt: "2026-09-17T09:15:00.000Z",
    priority: "HIGH",
    status: "IN_PROGRESS",
    ledgerHash: "#PMC-2026-SHA256-7819A",
    location: {
      ward: "Ward 8",
      zone: "Central Pune",
      address: "Lane 4, Near Bal Shikshan Mandir, Shaniwar Peth",
      latitude: 18.5196,
      longitude: 73.8553,
    },
    sla: {
      slaCode: "SLA-SAN-01",
      totalHours: 24,
      elapsedHours: 4,
      remainingHours: 20,
      deadlineIso: "2026-09-18T09:15:00.000Z",
      escalationLevel: 0,
      status: "ON_TRACK",
      tiers: [],
    },
    evidence: [],
    aiAnalysis: {
      category: "Sanitation & Solid Waste",
      subcategory: "Municipal Waste Collection",
      severityScore: 7.2,
      severityDescription: "Hygiene risk near educational institution",
      affectedPopulationEstimate: "~800 residents & school students",
      durationText: "4 days",
      jurisdiction: "PMC Sanitation Department",
      confidenceScore: 96.1,
      extractedEntities: ["Shaniwar Peth", "Bal Shikshan Mandir"],
      multimodalSummary: "Uncollected residential organic waste spilling onto walkway.",
    },
    similarComplaints: [],
    recommendation: {
      recommendedAction: "Dispatch morning tipper compactor truck #12 to Lane 4",
      rationale: "Proximity to elementary school requires priority clearance prior to noon recess.",
      expectedResolutionHours: 3,
      confidenceScore: 98.0,
      status: "ACCEPTED",
    },
    agentTimeline: [],
  },
  {
    id: "grv-2026-1040",
    grievanceNumber: "GRV-2026-1040",
    title: "Burst potable water pipeline flooding street near Kothrud Depot",
    description: "Major drinking water pipeline rupture wasting high pressure clean water.",
    originalTextLog: "Clean water pipeline broken, flooding traffic road.",
    language: "Marathi",
    citizen: {
      id: "usr-cit-03",
      name: "Suresh Patwardhan",
      uid: "IND-MH-PN-9921",
      isVerified: true,
      phoneMasked: "+91 94220 *****",
    },
    filedAt: "2026-09-16T15:20:00.000Z",
    priority: "CRITICAL",
    status: "ESCALATED",
    ledgerHash: "#PMC-2026-SHA256-1182C",
    location: {
      ward: "Ward 10",
      zone: "Kothrud Zone",
      address: "Paud Road, Opp. Kothrud Bus Depot",
      latitude: 18.5074,
      longitude: 73.8077,
    },
    sla: {
      slaCode: "SLA-WTR-02",
      totalHours: 12,
      elapsedHours: 14,
      remainingHours: 0,
      deadlineIso: "2026-09-17T03:20:00.000Z",
      escalationLevel: 2,
      status: "ESCALATED",
      tiers: [],
    },
    evidence: [],
    aiAnalysis: {
      category: "Water Supply & Sewage",
      subcategory: "Main Conduit Rupture",
      severityScore: 9.4,
      severityDescription: "Critical municipal resource loss & road sub-base erosion",
      affectedPopulationEstimate: "~35,000 households",
      durationText: "18 hours",
      jurisdiction: "PMC Water Supply Division",
      confidenceScore: 97.4,
      extractedEntities: ["Kothrud Depot", "Paud Road 300mm Feeder"],
      multimodalSummary: "High-pressure municipal potable main leaking 400 liters/minute.",
    },
    similarComplaints: [],
    recommendation: {
      recommendedAction: "Emergency valve shutdown and immediate excavation by repair team",
      rationale: "Escalated due to SLA breach and structural road integrity risk.",
      expectedResolutionHours: 6,
      confidenceScore: 99.0,
      status: "ACCEPTED",
    },
    agentTimeline: [],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "log-1",
    grievanceNumber: "GRV-2026-1042",
    timestamp: "2026-09-17T10:32:00.000Z",
    actorType: "CITIZEN",
    actorName: "Ramesh Kulkarni (Citizen)",
    action: "GRIEVANCE_SUBMITTED",
    details: "Case logged via NagrikAI Citizen Web App with 2 geotagged images and 1 voice audio transcript.",
  },
  {
    id: "log-2",
    grievanceNumber: "GRV-2026-1042",
    timestamp: "2026-09-17T10:34:10.000Z",
    actorType: "AI_AGENT",
    actorName: "NagrikAI Multimodal Vision & NLP Pipeline",
    action: "EVIDENCE_VERIFIED",
    details: "EXIF geotags verified within 12m. Manipulated risk: 0.04 (Low). Status assessed as LIKELY_AUTHENTIC.",
  },
  {
    id: "log-3",
    grievanceNumber: "GRV-2026-1042",
    timestamp: "2026-09-17T10:34:45.000Z",
    actorType: "AI_AGENT",
    actorName: "NagrikAI Classifier & Decision Engine",
    action: "SEVERITY_INDEXED",
    details: "Hazard scored at 8.8/10 (HIGH PRIORITY). Extracted dual jurisdiction: PMC Civil + MSEDCL Electrical.",
  },
  {
    id: "log-4",
    grievanceNumber: "GRV-2026-1042",
    timestamp: "2026-09-17T10:35:12.000Z",
    actorType: "AI_AGENT",
    actorName: "LangGraph Follow-up Sentinel Agent",
    action: "TICKET_ROUTED",
    details: "Dispatched to PMC Ward 12 Executive Engineering division. Official email and in-app alert dispatched.",
  },
  {
    id: "log-5",
    grievanceNumber: "GRV-2026-1042",
    timestamp: "2026-09-17T11:20:00.000Z",
    actorType: "OFFICER",
    actorName: "Er. Rajesh Sharma (Executive Engineer)",
    action: "AUTHORITY_DIRECTIVE_LOGGED",
    details: "Inspection squad deployed with electrical wing. Cold asphalt compaction scheduled for 18 Sep 10:30 AM.",
  },
  {
    id: "log-6",
    grievanceNumber: "GRV-2026-1042",
    timestamp: "2026-09-17T11:22:15.000Z",
    actorType: "AI_AGENT",
    actorName: "NagrikAI Broadcast Sentinel",
    action: "CITIZEN_NOTIFIED",
    details: "Sent automated multi-channel progress update to citizen via SMS and WhatsApp.",
  },
];
